[project]
name = "matematicas-con-juan"
version = "0.1.0"
description = "Repositorio central de ejercicios de matemáaticas"
readme = "README.md"
authors = [
    { name = "cr2003", email = "crodrigo2003@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.2.0",
    "setuptools>=82.0.1",
    "sympy>=1.14.0",
    "vpython>=7.6.5",
]

[tool.uv.workspace]
members = ["Algebra", "Numeros_Complejos", "Trigonometria"] # Añade aquí tus carpetas actuales

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
