[project]
name = "numeros-complejos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "cr2003", email = "crodrigo2003@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
numeros-complejos = "numeros_complejos:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
